apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    name: chat
    env: staging
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: chat
    env: staging
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: chat
    env: staging
  name: chat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chat
        env: staging
        version: "0.9.5"
    spec:
      containers:
      - env:
        - name: SECRET_KEY_BASE
          value: 265728C3CEE6D163E3A210D2C7952CF50EF3E1765E3FB69DC13E70C93E6D0EF8
        - name: DB_USERNAME
          value: klzii
        - name: DB_PASSWORD
          value: VQqttpXdE42u6PUKWusy
        - name: DB_HOST
          value: klzii-staging.cyujokxcbe0c.us-west-2.rds.amazonaws.com
        - name: DB_DATABASE
          value: klzii_staging
        - name: SERVER_HOST
          value: chat.klzii.com
        - name: GUARDIAN_SECRET_KEY
          value: "SttPra/cddsnX+Vko2i8KA=="
        image: 944561038201.dkr.ecr.us-west-2.amazonaws.com/klzii_chat:latest
        name: chat
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
data:
  proxycert: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZKakNDQkE2Z0F3SUJBZ0lJZFFsQkExT2xmL0l3RFFZSktvWklodmNOQVFFTEJRQXdnYlF4Q3pBSkJnTlYKQkFZVEFsVlRNUkF3RGdZRFZRUUlFd2RCY21sNmIyNWhNUk13RVFZRFZRUUhFd3BUWTI5MGRITmtZV3hsTVJvdwpHQVlEVlFRS0V4RkhiMFJoWkdSNUxtTnZiU3dnU1c1akxqRXRNQ3NHQTFVRUN4TWthSFIwY0RvdkwyTmxjblJ6CkxtZHZaR0ZrWkhrdVkyOXRMM0psY0c5emFYUnZjbmt2TVRNd01RWURWUVFERXlwSGJ5QkVZV1JrZVNCVFpXTjEKY21VZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eWFYUjVJQzBnUnpJd0hoY05NVFl3TkRFNE1EZ3lPRE00V2hjTgpNVGN3TkRFNE1EZ3lPRE00V2pBNU1TRXdId1lEVlFRTEV4aEViMjFoYVc0Z1EyOXVkSEp2YkNCV1lXeHBaR0YwClpXUXhGREFTQmdOVkJBTU1DeW91YTJ4NmFXa3VZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBeUpabkswaFdsLzI5NE12alMwOGoxdEtkdGEwQUNyd0RjUGFSTlA0elh6czZDZzhvb3hUdgpFVFFCc2NMMWJQNC9UOUE3ZEROem9CS05FbnlqZGVpVUxpSEtySXdJWWsxV0ttM2FlNnArWUNFT3JuTG5Od3l0CnVGQVBXTm5Yc3pXL0ZIRVY1NkIybVNXSUI1aXlQaS8xNjdueTFuRTdkNjRxS015TGJ4R0ZkSW0zbkxsNXdSemcKVzNGQmR6S2NuUUx0UVAvd3lNRUpVK0hiOEFOU2h6Mit3blh6SjhhWWdMaEJhOE53V0ZuME5acnYxTGMrS0V6NQpob3ZoOFZpVVpTR1JMVjdUS2o1cGVCcG5RdTlYNk1XMHdRN0U3VlBFb1BrUVJVbk81RmtoWHB6bEhaZjdwZDdYCjVtNHRCTzQraHVaRDhvdkdPY1Y1R3FrSjdld0tkTzNvRVFJREFRQUJvNElCdERDQ0FiQXdEQVlEVlIwVEFRSC8KQkFJd0FEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3RGdZRFZSMFBBUUgvQkFRRApBZ1dnTURjR0ExVWRId1F3TUM0d0xLQXFvQ2lHSm1oMGRIQTZMeTlqY213dVoyOWtZV1JrZVM1amIyMHZaMlJwClp6SnpNUzB5TWpVdVkzSnNNRjBHQTFVZElBUldNRlF3U0FZTFlJWklBWWI5YlFFSEZ3RXdPVEEzQmdnckJnRUYKQlFjQ0FSWXJhSFIwY0RvdkwyTmxjblJwWm1sallYUmxjeTVuYjJSaFpHUjVMbU52YlM5eVpYQnZjMmwwYjNKNQpMekFJQmdabmdRd0JBZ0V3ZGdZSUt3WUJCUVVIQVFFRWFqQm9NQ1FHQ0NzR0FRVUZCekFCaGhob2RIUndPaTh2CmIyTnpjQzVuYjJSaFpHUjVMbU52YlM4d1FBWUlLd1lCQlFVSE1BS0dOR2gwZEhBNkx5OWpaWEowYVdacFkyRjAKWlhNdVoyOWtZV1JrZVM1amIyMHZjbVZ3YjNOcGRHOXllUzluWkdsbk1pNWpjblF3SHdZRFZSMGpCQmd3Rm9BVQpRTUs5SjQ3TU5JTXdvalBYKzJ5ejhMUXNnTTR3SVFZRFZSMFJCQm93R0lJTEtpNXJiSHBwYVM1amIyMkNDV3RzCmVtbHBMbU52YlRBZEJnTlZIUTRFRmdRVWl0V01FM3FuU0IyTzRXWVlleTZHQ2pldHFnWXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUlNMlh4dTNUUDRUcDl3V293SlFScWZLY0p1L2Q0SWtzNnlmTlNFcFpBUENYVmIyc0JxKwpZaU1Fd2pNcU84dDh6SDBrT3dnOW1rc1FVR2VhYkFvcG1IbDE4bUdOOWdKbmdKcVRHMk0vQUU5Q0ZOMnJaT2pBClE4aFFqRXRvaGxDek8yNlpGOEdNazVmbEtvMk5FOGZJUE5lKzZNclVrMVArSmFhTE1FVlA2cUQxOG5CeHpnNTUKK0RrdUptbWpaWUZ1UjNyRERuU1dRelRkUnhMdnF2U0NPYXJzY2d4UEJHckxXVm1RbGFmSVZXL3E3VWF4dW1PZgo5MlhqbUhlSURjL0RzR01XWTZqcGdTMnhYczEvWTFia2xYMzF2K0ptN1NOcG5wUytpMzZKZTBrREdWb3Z1QlViCkVEdkdhRlFVZjN6czZ5bHNnUkJOcEc2VWlac2dlMlgvdktJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFMERDQ0E3aWdBd0lCQWdJQkJ6QU5CZ2txaGtpRzl3MEJBUXNGQURDQmd6RUxNQWtHQTFVRUJoTUNWVk14CkVEQU9CZ05WQkFnVEIwRnlhWHB2Ym1FeEV6QVJCZ05WQkFjVENsTmpiM1IwYzJSaGJHVXhHakFZQmdOVkJBb1QKRVVkdlJHRmtaSGt1WTI5dExDQkpibU11TVRFd0x3WURWUVFERXloSGJ5QkVZV1JrZVNCU2IyOTBJRU5sY25ScApabWxqWVhSbElFRjFkR2h2Y21sMGVTQXRJRWN5TUI0WERURXhNRFV3TXpBM01EQXdNRm9YRFRNeE1EVXdNekEzCk1EQXdNRm93Z2JReEN6QUpCZ05WQkFZVEFsVlRNUkF3RGdZRFZRUUlFd2RCY21sNmIyNWhNUk13RVFZRFZRUUgKRXdwVFkyOTBkSE5rWVd4bE1Sb3dHQVlEVlFRS0V4RkhiMFJoWkdSNUxtTnZiU3dnU1c1akxqRXRNQ3NHQTFVRQpDeE1rYUhSMGNEb3ZMMk5sY25SekxtZHZaR0ZrWkhrdVkyOXRMM0psY0c5emFYUnZjbmt2TVRNd01RWURWUVFECkV5cEhieUJFWVdSa2VTQlRaV04xY21VZ1EyVnlkR2xtYVdOaGRHVWdRWFYwYUc5eWFYUjVJQzBnUnpJd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNTRNc1ExSzkydmRTVFl1c3daTGlCQ0d6RApCTmxpRjQ0di96NWx6NC9PWXVZOFVoemFGa1ZMVmF0NGEyT0RZcERPRDJsc21jZ2FGSXRNekVVejZvamNucU92CksvNkFZWjE1VjhUUEx2US9NRHhkUi95YUZyekRONVpCVVk0UlMxVDRLTDdRakw3d01EZ2U4N0FtK0daSFkyM2UKY1NaSGp6aEhVOUZHSGJUajNBRHFSYXk5dkhIWnFtOEEyOXZOTURwNVQxOU1SL2dkNzF2Q3hKMWdPN0d5UTVIWQpwRE5PNnJQV0owK3RKWXFseHZUVjBLYXVkQVZrVjRpMVJGWFVMU282UHZpNHZla3lDZ0tVWk1RV09sRHhTcTduCmVUT3ZEQ0FIZitqZkJEbkNhUUpzWTFMNmQ4RWJ5SFNIeUxtVEdGQlVOVXRwVHJ3NzAwa3VIOXpCMGxMN0FnTUIKQUFHamdnRWFNSUlCRmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUJCakFkQmdOVgpIUTRFRmdRVVFNSzlKNDdNTklNd29qUFgrMnl6OExRc2dNNHdId1lEVlIwakJCZ3dGb0FVT3BxRkJ4Qm5LTGJ2CjlyMEZRVzRnd1pUYUQ5NHdOQVlJS3dZQkJRVUhBUUVFS0RBbU1DUUdDQ3NHQVFVRkJ6QUJoaGhvZEhSd09pOHYKYjJOemNDNW5iMlJoWkdSNUxtTnZiUzh3TlFZRFZSMGZCQzR3TERBcW9DaWdKb1lrYUhSMGNEb3ZMMk55YkM1bgpiMlJoWkdSNUxtTnZiUzluWkhKdmIzUXRaekl1WTNKc01FWUdBMVVkSUFRL01EMHdPd1lFVlIwZ0FEQXpNREVHCkNDc0dBUVVGQndJQkZpVm9kSFJ3Y3pvdkwyTmxjblJ6TG1kdlpHRmtaSGt1WTI5dEwzSmxjRzl6YVhSdmNua3YKTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBSWZteVRFTWc0dUphcGtFdi9vVjlQQk85c1BweUlCc2xRajZaego5MWN4Rzc2ODVDL2IrTHJUVytDMDUrWjVZZzRNb3RkcVkzTXh0ZldvU0tRN0NDMmlYWkRYdEh3bFR4RldNTVMyClJKMTdMSjNsWHVidkRHR3F2K1FxRys2RW5yaURmY0ZEemtTbkUzQU5rUi8weUJPdGcyRFoySEtvY3lRZXRhd2kKRHNvWGlXSllSQnVyaVNVQkFBL054QnRpMjFHMDB3OVJLcHYwdkhQOGRzNDJwTTNaMkN6cXJwdjFLcktRMFUxMQpHSW8vaWtHUUkzMWJTLzZrQTFpYlJyTERZR0NEK0gxUVFjN0NvWkREdSs4Q0w5SVZWTzVFRmRrS3JxZUtNKzJ4CkxYWTJKdHdFNjUvM1lSOFYzSWR2N2thV0tLMmhKbjBLQ2FjdUJLT052UGk4QkRBQgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFZlRDQ0EyV2dBd0lCQWdJREcrY1ZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1HTXhDekFKQmdOVkJBWVRBbFZUCk1TRXdId1lEVlFRS0V4aFVhR1VnUjI4Z1JHRmtaSGtnUjNKdmRYQXNJRWx1WXk0eE1UQXZCZ05WQkFzVEtFZHYKSUVSaFpHUjVJRU5zWVhOeklESWdRMlZ5ZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrd0hoY05NVFF3TVRBeApNRGN3TURBd1doY05NekV3TlRNd01EY3dNREF3V2pDQmd6RUxNQWtHQTFVRUJoTUNWVk14RURBT0JnTlZCQWdUCkIwRnlhWHB2Ym1FeEV6QVJCZ05WQkFjVENsTmpiM1IwYzJSaGJHVXhHakFZQmdOVkJBb1RFVWR2UkdGa1pIa3UKWTI5dExDQkpibU11TVRFd0x3WURWUVFERXloSGJ5QkVZV1JrZVNCU2IyOTBJRU5sY25ScFptbGpZWFJsSUVGMQpkR2h2Y21sMGVTQXRJRWN5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2M0ZpCkNQSDZXVFQzRzhrWW8vZUFTVmpwSW9NVHBzVWdRd0U3aFBIbWhVbWZKK3IyaEJ0T29MVGJjSmpITWdHeEJUNEgKVHU3MCtrOHZXVEFpNTZzWlZtdmlnQWY4OHhaMWdEbFJlK1g1TmJaMFRxbU5naFBrdGorcEE0UDZvcjZLRldwLwozZ3ZEdGhrVUJjcnF3NmdFbER0R2ZESU44d0JtSXNpTmFXMDJqQkVZdDlPeUhHQzBPUG9Dak03VDNVWUgzZ28rCjYxMTh5SHo3c0N0VHBKSmlhVkVsQldFYVJJR01MS2xEbGlQZnJEcUJtZzRweFJ5cDZWMGV0cDZlTUFvNXp2R0kKZ1B0TFhjd3k3SVZpUXlVMEFsWW5BWkcwTzNBcVAyNng2SnlJQVgyZjFQbmJVMjFnbmI4czUxaXJ1RjlHL003RQpHd004Q2V0Sk1WeHBSclBnUndJREFRQUJvNElCRnpDQ0FSTXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FRWXdIUVlEVlIwT0JCWUVGRHFhaFFjUVp5aTI3L2E5QlVGdUlNR1UyZy9lTUI4R0ExVWQKSXdRWU1CYUFGTkxFc05LUjFFd1JjYk5oeXoyaC90Mm9hdFRqTURRR0NDc0dBUVVGQndFQkJDZ3dKakFrQmdncgpCZ0VGQlFjd0FZWVlhSFIwY0RvdkwyOWpjM0F1WjI5a1lXUmtlUzVqYjIwdk1ESUdBMVVkSHdRck1Da3dKNkFsCm9DT0dJV2gwZEhBNkx5OWpjbXd1WjI5a1lXUmtlUzVqYjIwdloyUnliMjkwTG1OeWJEQkdCZ05WSFNBRVB6QTkKTURzR0JGVWRJQUF3TXpBeEJnZ3JCZ0VGQlFjQ0FSWWxhSFIwY0hNNkx5OWpaWEowY3k1bmIyUmhaR1I1TG1OdgpiUzl5WlhCdmMybDBiM0o1THpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVdRdFR2WktHRWFja2UrMWJNYzhkCkgyeHd4Ymh1dms2NzlyNlhVT0V3Zjdvb1hHS1V3dU4rTS9mN1FuYUYyNVVjakNKWWRRa01pR1ZuT1FvV0NjV2cKT0pla3hTT1RQN1FZcGdFR1JKSGpwMmtudEZvbGZ6cTNNczNkaFA4cU9Da3pwTjFuc29YK29ZZ2dIRkNKeU53cQo5a0lETjB6bWlOL1ZyeVR5c2NQZnpMWHM0SmxldDBsVUlEeVVHQXpISEZJWVNhUnQ0Yk5ZQzhuWTdObXVIREtPCktIQU40djZtRjU2RUQ3MVhjTE5hNlIrZ2hsTzc3M3ovYVF2Z1NNTzNrd3ZJQ2xURXJGMFVaemRzeXFVdk1RZzMKcW01dmpMeWI0bGRkSklHdmw1ZWNoSzFzckRkTVp2TmhrUkVnNUw0d24zcWtLUW13NFRSZlpIY1lRRkhmakRDbQpydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBRENDQXVpZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRVUZBREJqTVFzd0NRWURWUVFHRXdKVlV6RWgKTUI4R0ExVUVDaE1ZVkdobElFZHZJRVJoWkdSNUlFZHliM1Z3TENCSmJtTXVNVEV3THdZRFZRUUxFeWhIYnlCRQpZV1JrZVNCRGJHRnpjeUF5SUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNQjRYRFRBME1EWXlPVEUzCk1EWXlNRm9YRFRNME1EWXlPVEUzTURZeU1Gb3dZekVMTUFrR0ExVUVCaE1DVlZNeElUQWZCZ05WQkFvVEdGUm8KWlNCSGJ5QkVZV1JrZVNCSGNtOTFjQ3dnU1c1akxqRXhNQzhHQTFVRUN4TW9SMjhnUkdGa1pIa2dRMnhoYzNNZwpNaUJEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVUQ0NBU0F3RFFZSktvWklodmNOQVFFQkJRQURnZ0VOCkFEQ0NBUWdDZ2dFQkFONmQxK3BYR0VtaFcrdlhYMGlHNnI3ZC8rVHZaeHowWldpelYzR2dYbmU3N1p0SjZYQ0EKUFZZWVl3aHYydkxNMEQ5L0FsUWlWQkRZc29IVXdIVTlTMy9IZDhNK2VLc2FBN1VnYXk5cUs3SEZpSDdFdXg2dwp3ZGhGSjIrcU4xajNoeWJYMkMzMnFSZTNIM0kyVHFZWFAyV1lrdHNxYmwyaS9vamdDOTUvNVkwVjRldkxPdFhpCkVxSVRMZGlPcjE4U1BhQUlCUWkyWEtWbE9BUkZtUjZqWUdCMHhVR2xjbUliWXNVZmIxOGFRcjRDVVdXb3JpTVkKYXZ4NEE2bE5mNEREK3F0YS9LRkFwTW9aRnY2eXlPOWVjdzN1ZDcyYTlubVl2TEVIWjZJVkRkMmdXTVpFZXdvKwpZaWhmdWtFSFUxalBFWDQ0ZE1YNC83VnBrSStFZE9xWEc2OENBUU9qZ2NBd2diMHdIUVlEVlIwT0JCWUVGTkxFCnNOS1IxRXdSY2JOaHl6MmgvdDJvYXRUak1JR05CZ05WSFNNRWdZVXdnWUtBRk5MRXNOS1IxRXdSY2JOaHl6MmgKL3Qyb2F0VGpvV2VrWlRCak1Rc3dDUVlEVlFRR0V3SlZVekVoTUI4R0ExVUVDaE1ZVkdobElFZHZJRVJoWkdSNQpJRWR5YjNWd0xDQkpibU11TVRFd0x3WURWUVFMRXloSGJ5QkVZV1JrZVNCRGJHRnpjeUF5SUVObGNuUnBabWxqCllYUnBiMjRnUVhWMGFHOXlhWFI1Z2dFQU1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFRkJRQUQKZ2dFQkFESkw4N0xLUHBIOEVzYWhCNHlPZDZBekJoUmNrQjRZOXdpbVBRb1orWWVBRVc1cDVKWVhNUDgwa1dOeQpPTzdNSEFHakhaUW9wREgyZXNSVTEvYmxNVmdEb3N6T1l0dVVSWE8xdjBYSkpMWFZnZ0t0STNscGpiaTJUYzdQClRNb3pJK2djaUtxZGkwRnVGc2tnNVltZXpUdmFjUGQrbVNZZ0ZGUWxxMjV6aGVhYklaMEtiSUlPcVBqQ0RQb1EKSG15Vzc0Y054QTloaTYzdWd5dVYrSTZTaEhJNTZ5RHFnKzJEelpkdUNMenJUaWEyY3l2azAvWk0vaVp4NG1FUgpkRXIvVnhxSEQzVklMczlSYVJlZ0FoSmhsZFhSUUxJUVRPN0VyQkJEcHFXZUN0V1ZZcG9OejRpQ3hUSU01Q3VmClJlWU5ueWljc2JrcVdsZXROdyt2SFgvYnZaOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='
  dhparam: 'LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQkNBS0NBUUVBdVpxZUtSRUdhOUhOMTZYV2szMnpiL3B1UjJuUW8zZmtXbmExVmsvNVhpcFBKYXdobS9hWgpCUlZuSE5KZ1BEdzhwMElUT0JpeGdtVXlYdmdtb0tOUm9Oa1NMZkpoWXl1VzBGdUNVNklQcVFLeGMxRnlYSEJRClRkMnd2V1pKb1d2RGNRSmFJSktOZFAzd3RrNXR6UFY1ZEUwNnl2ajc1bTZkdmlINkpIdlZSQXl4YUhDL3lzRzUKeTlsMWh5Z2tadFlCYVNjRTlHUHNJUGRxclNRQmxGTjNRdHk0T3FaVXVQYVUvOUx6MGNBc2lkMU9DRjR5NnlFMQpoREFjbXI2V0tFZndQa3ZpVWpGbkg5SFEyRDZHa0N0Wk9zZVUxMTVCR0hHblp1MTllakZwSzB2YWJnb1d5SFpOCjk4WkV4ZkJNM1cveEJJTUxORnE0R2cxaHc1RFowMVhuWXdJQkFnPT0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg=='
  proxykey: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRElsbWNyU0ZhWC9iM2cKeStOTFR5UFcwcDIxclFBS3ZBTnc5cEUwL2pOZk96b0tEeWlqRk84Uk5BR3h3dlZzL2o5UDBEdDBNM09nRW8wUwpmS04xNkpRdUljcXNqQWhpVFZZcWJkcDdxbjVnSVE2dWN1YzNESzI0VUE5WTJkZXpOYjhVY1JYbm9IYVpKWWdICm1MSStML1hydWZMV2NUdDNyaW9vekl0dkVZVjBpYmVjdVhuQkhPQmJjVUYzTXB5ZEF1MUEvL0RJd1FsVDRkdncKQTFLSFBiN0NkZk1ueHBpQXVFRnJ3M0JZV2ZRMW11L1V0ejRvVFBtR2krSHhXSlJsSVpFdFh0TXFQbWw0R21kQwo3MWZveGJUQkRzVHRVOFNnK1JCRlNjN2tXU0Zlbk9VZGwvdWwzdGZtYmkwRTdqNkc1a1B5aThZNXhYa2FxUW50CjdBcDA3ZWdSQWdNQkFBRUNnZ0VBQVJyYS9LRU1ZUS96d000K3RVWjlVd3liODhrOUs5SDNUdUw4ejhicXI0YWEKL2oweEl4elZhRW5hREltZlluZFFEL2Q4ckZvd005eUdUR2pGV2J2clBRblFuUHkwZXg0ajhGM2tpelBZT0YxVwpRRjIvcWt6MmxBSlU0MDluNGNQVkJwN00yUmJJTUhYRmR3MC9SaHByaDEzaDJZNk1IayttU2MwK28yRDhWRFQvCmZuYm1qNHl1QmZXUjVUc2s4RGMzWWRBY2Y1LzF2Wnd5NWNRZDRzUnc0dU1MNzQ3OFFmRmQwbTZ5WWZFZXpFTlkKV0FaZU14K1RxOGxoQzAwQUo4OXlXY0VCZnRjZ2Y3RUpUdWpONW9CNE9yYWVEK200S1BwQmgrZzUyTUdiLy9wdwo1Y2p4NEtBQXpaN3NtYjB2QlN2dnpzSDhIWVFBcXNWSmhSbEVWem5iUVFLQmdRRHgzNVZxZmpIaDRZQWNqMXdmCmJkaElLM2ZrZWJJVDM0ZlZvZW1hMHlsRkRTdStHQ0VLTG1wTjhRenVrSXM4a0lyRVZVRGg4eW1EejBwUXQ5SWIKL1hycUF5N1p2M3pDSW1MTUMzd3B1QjBmekNoQzFrV3ZYcmY1TStWUHdaOTZXVnRNbjdlUFBIOUh3WFVKWjQ0RwpGTE51VlA0MmxhNmlndGRBLzcrVzdyOGJXUUtCZ1FEVVRZYWN4VHE0aHY2NGpGU1lsZUhqZDhDTytsaHpSd0p3CnMzOWZKSm9LSS9hbmcwcnFqNDZtVTFlYysrMWxITTUvbjVQOElBWFNXd2cvTVB2ZFBLenJ6eW9mMGRtR0lrZVAKNktmS3NYVzIzWnQvbGlWdTAxVkxiY0RjQzdXU0NlaFU5b3JiVjdxOUZrWkhUNFg1eWltaFd3cDF3Y29mRmhROAo5TFVCQUxsemVRS0JnUURaZnlnbzN0bVVPT2F1eCtzYkIvZVl6aDI5Z2dFMEJhbHIzWERuSEVMY0tQL1FySG5wCllkdU53dGpTSFlCWE1kTFd3YUxhaTRJbFdOMkd3QVZiemhBZEprZVczcTRkRkRhckxSaTFteTMxVGV4V1RiL1QKOXVTUVhxNHhqZmNPV2hQVFR6d012V1htN0h1RnZXems0dkNHb2o4R2JvcmU3N0VJYmZHbWs0R2Q0UUtCZ0U2bgpTaS9hZ2g3TEpLT0ttZXpOMnBwRFMzdXRGQWZoVHU0aUVoWlZvUndRcHRqNHMxQ2pUdDRnRWwxK21EelZwMHR3Cis0cDA4ck0wTnFIeXE5MFRGWjFuYXR2UEN4KytvM1NWWlZTYTJsbWRVSGE4VWJIMWFheEFSU3RBeTB3SGo2T3EKazFjZjhYY01RWTA1MFJEeDdPcHlxRFZvVGxHbUJHbHczMzQzbm4xQkFvR0JBTE5NbFZvMFBIQVZ1YkM0TWlIKwpxUWtqc0Z3cnp5VUlkOW5BUzR3THQ3OUhtYWdzZmxETW9hWWhYa2xBZlB0OGhPWVh0ZThHeGl3dnJXVUlLR0FzCnYzb1dSZEJmM2ZhMW5tOExKMjBJYTl3ZE1DVG12Z3VVOTBqR1oxS0FLVGUzdmsyOUlkVFJiVzNTMWViOUVPTGcKRlZwYjZZR1lpUm9LU1lKa3NhYy90cCtHCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K'
kind: Secret
metadata:
  name: ssl-proxy-secret
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: proxy-chat-staging
  labels:
    name: nginx
    role: ssl-proxy
    app: chat
    env: staging
spec:
  ports:
  - name: https
    port: 443
    targetPort: ssl-proxy-https
    protocol: TCP
  - name: http
    port: 80
    targetPort: ssl-proxy-http
    protocol: TCP
  selector:
    name: nginx
    role: ssl-proxy
    app: chat
    env: staging
  type: LoadBalancer
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: proxy-chat-staging
  labels:
    name: nginx
    role: ssl-proxy
    app: chat
    env: staging
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
    app: chat
    env: staging
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
        app: chat
        env: staging
    spec:
      containers:
      - name: nginx-ssl-proxy
        image: 944561038201.dkr.ecr.us-west-2.amazonaws.com/nginx-ssl-proxy:latest
        env:
        - name: SERVICE_HOST_ENV_NAME
          value: CHAT_SERVICE_HOST
        - name: SERVICE_PORT_ENV_NAME
          value: CHAT_SERVICE_PORT
        - name: ENABLE_SSL
          value: 'true'
        ports:
        - name: ssl-proxy-http
          containerPort: 80
        - name: ssl-proxy-https
          containerPort: 443
        volumeMounts:
        - name: ssl-proxy-secret
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: ssl-proxy-secret
        secret:
          secretName: ssl-proxy-secret
