apiVersion: v1
data:
  proxycert: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZiRENDQkZTZ0F3SUJBZ0lKQU1wNkZiVXNvUXRDTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUcwTVFzd0NRWUQKVlFRR0V3SlZVekVRTUE0R0ExVUVDQk1IUVhKcGVtOXVZVEVUTUJFR0ExVUVCeE1LVTJOdmRIUnpaR0ZzWlRFYQpNQmdHQTFVRUNoTVJSMjlFWVdSa2VTNWpiMjBzSUVsdVl5NHhMVEFyQmdOVkJBc1RKR2gwZEhBNkx5OWpaWEowCmN5NW5iMlJoWkdSNUxtTnZiUzl5WlhCdmMybDBiM0o1THpFek1ERUdBMVVFQXhNcVIyOGdSR0ZrWkhrZ1UyVmoKZFhKbElFTmxjblJwWm1sallYUmxJRUYxZEdodmNtbDBlU0F0SUVjeU1CNFhEVEUyTURrd01qQXhOVE16T1ZvWApEVEU0TURrd01qQXhOVE16T1Zvd2NqRUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdUQ2xGMVpXVnVjMnhoCmJtUXhGREFTQmdOVkJBY1RDMEp2ZDJWdUlFaHBiR3h6TVNFd0h3WURWUVFLRXhoVWFHbHlaQ0JYWVhabElFMWwKWkdsaElGQjBlU0JNZEdReEZUQVRCZ05WQkFNTURDb3VhMng2YVdrdVkyaGhkRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlpKRWdhOEZqWkNNdWZ0MjhDR0s1L1RoMnM1bjdKelV2YVBYTTc2CisyeVBMRXZtaG56N0JhenVyUFp4TDJwWHlQVVZwK2o2ZUw1ZDNRRlFXTjh0Y2JmRmllRXdUWi93REhtSHlYWEkKU2J6eE9qMUlZRWl4YkhPcGNBN0tFYlRSbU5SZVNLNjRWVHBxQ2cwR3poZU42WjNabkFQRmtXSzBjcjJrSkFIKwpjQWJjNG5kZzB4TCtWemZKcm14OWMyeXU1MllSVldLWkVDelltQmVkMTBEUWtLTjlIdUY5L1Q0K2NFc08vM2RyCjlQVXU1Q0h6V0tEZVhoUXpoQnlsMEFiSS9QWjhpVW8wOVJhR1JqNzVCY2RSNW5LNWNhOS9TYVIxb3N6Y2cxeHAKOWtpdFNDdUtCTXAwaWNKWkw5a0p6NDBuVHIvYm5ZUVlkdDNEak54UTdTK3d5ejBDQXdFQUFhT0NBY0F3Z2dHOApNQXdHQTFVZEV3RUIvd1FDTUFBd0tRWURWUjBsQkNJd0lBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNCZ3BnCmhrZ0JodmhOQVFJRE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBMUJnTlZIUjhFTGpBc01DcWdLS0FtaGlSb2RIUncKT2k4dlkzSnNMbWR2WkdGa1pIa3VZMjl0TDJka2FXY3ljekl0TXk1amNtd3dYUVlEVlIwZ0JGWXdWREJJQmd0Zwpoa2dCaHYxdEFRY1hBakE1TURjR0NDc0dBUVVGQndJQkZpdG9kSFJ3T2k4dlkyVnlkR2xtYVdOaGRHVnpMbWR2ClpHRmtaSGt1WTI5dEwzSmxjRzl6YVhSdmNua3ZNQWdHQm1lQkRBRUNBakIyQmdnckJnRUZCUWNCQVFScU1HZ3cKSkFZSUt3WUJCUVVITUFHR0dHaDBkSEE2THk5dlkzTndMbWR2WkdGa1pIa3VZMjl0THpCQUJnZ3JCZ0VGQlFjdwpBb1kwYUhSMGNEb3ZMMk5sY25ScFptbGpZWFJsY3k1bmIyUmhaR1I1TG1OdmJTOXlaWEJ2YzJsMGIzSjVMMmRrCmFXY3lMbU55ZERBZkJnTlZIU01FR0RBV2dCUkF3cjBuanN3MGd6Q2lNOWY3YkxQd3RDeUF6akFqQmdOVkhSRUUKSERBYWdnd3FMbXRzZW1scExtTm9ZWFNDQ210c2VtbHBMbU5vWVhRd0hRWURWUjBPQkJZRUZIWWl2QnVQUGh5SwpZa1BkdGlmZThXZmxQbENPTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBM3NBVEdHM2xudnF6aUQwTkN5bWNCCjRzemZNOXNlY3NwUGp2NG5GWjRaai8vNCtoSm1Nb3BRZXlFMHpNVnQ4Ylk1VmQ3Z3VTZlRNditJWHErcmlNMFgKY1lNM2RtM3YvZmhMdi9VMGltQWQ3N1RjY09IckxxK1ExSmVKc1JUTEw3akMzcEE5OHRCY0NENFFxQ1Yzc1hlUwowaExsQnFna2kyS0lDOTFqR0R0Ym9KNkViNzc4bkdzbk9aTjZUQlpCcGV1UnFvcVNlMDdzeEVET2Z5RjJpa3U0CnNkN05EelJRMklrTTZaZk5wdzFNbmtnejNxOXE2a2xqTkhJQTlJM2FyeFl5VHhjNnR1cE1pdWNaVnhjK0VYOUEKV0FPdXVYV29nZHBKYnExMzVaeUxHalhONU1XSDk4L21hNWh1VDlUSXROUDIxL1YyajlyWDFENGRjZW9jRUNhbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=='
  dhparam: 'LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQkNBS0NBUUVBdVpxZUtSRUdhOUhOMTZYV2szMnpiL3B1UjJuUW8zZmtXbmExVmsvNVhpcFBKYXdobS9hWgpCUlZuSE5KZ1BEdzhwMElUT0JpeGdtVXlYdmdtb0tOUm9Oa1NMZkpoWXl1VzBGdUNVNklQcVFLeGMxRnlYSEJRClRkMnd2V1pKb1d2RGNRSmFJSktOZFAzd3RrNXR6UFY1ZEUwNnl2ajc1bTZkdmlINkpIdlZSQXl4YUhDL3lzRzUKeTlsMWh5Z2tadFlCYVNjRTlHUHNJUGRxclNRQmxGTjNRdHk0T3FaVXVQYVUvOUx6MGNBc2lkMU9DRjR5NnlFMQpoREFjbXI2V0tFZndQa3ZpVWpGbkg5SFEyRDZHa0N0Wk9zZVUxMTVCR0hHblp1MTllakZwSzB2YWJnb1d5SFpOCjk4WkV4ZkJNM1cveEJJTUxORnE0R2cxaHc1RFowMVhuWXdJQkFnPT0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg=='
  proxykey: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRFdTUklHdkJZMlFqTG4KN2R2QWhpdWYwNGRyT1oreWMxTDJqMXpPK3Z0c2p5eEw1b1o4K3dXczdxejJjUzlxVjhqMUZhZm8rbmkrWGQwQgpVRmpmTFhHM3hZbmhNRTJmOEF4NWg4bDF5RW04OFRvOVNHQklzV3h6cVhBT3loRzAwWmpVWGtpdXVGVTZhZ29OCkJzNFhqZW1kMlp3RHhaRml0SEs5cENRQi9uQUczT0ozWU5NUy9sYzN5YTVzZlhOc3J1ZG1FVlZpbVJBczJKZ1gKbmRkQTBKQ2pmUjdoZmYwK1BuQkxEdjkzYS9UMUx1UWg4MWlnM2w0VU00UWNwZEFHeVB6MmZJbEtOUFVXaGtZKworUVhIVWVaeXVYR3ZmMG1rZGFMTTNJTmNhZlpJclVncmlnVEtkSW5DV1MvWkNjK05KMDYvMjUyRUdIYmR3NHpjClVPMHZzTXM5QWdNQkFBRUNnZ0VBTzE0aE5XWjB6UEdJUXdOK1I1ZWtqSEpCYVc2Y2xRY29iQkVLQ0hvMm9Ed0cKYkx6Z2M4M2tJNlk0bTBwK2RYcit2UkFUNWhORzBvOFV4T0ZxemVJOFNFcmRTVnRsbGpNZWNha3lJb1NzRVVIUAovZHlJZUh0WGJhLzYwTTRoRzdTYUgvUkROTXp6Sit6cS9mTHR0RTduODRpdmxjZnQ0S2ZYeGp5c2tUVForcnhECjRpTEUwMVhpRmdsYjd4ek8xZVdoK1lITU5NK2p6R3ZNRld1a2RsZGh4SEN3VUdFRWw2eHpUUG1lRFAzV281cUMKT05HUnRsUjVRaUgzUUwxMDh6Q0RlWkRCQWp2OUlIaEZjQWFNWUcyRHF3Slg1N01JN1dQczdSVGd5ZzJpRkQ1bQplb3lKVHdzUGRnTTRLSlNGT0VRMksyaTRiRUNDTGtFRDZ4ck5kSG1xelFLQmdRRHQ0b2llcHU1cXM1TkhxMDJOCitzT3RGTVQzaXVlcUR4M3MvL21wWjRHdkRTWTVXSS8xb2E2SEVmZm1KRDhXTXAyNDYxTTBWREpLd2hzYXhoRXAKT1lNd25BSURUV1dTUmFZN29OMkE3NURJRzhXTXBVY3p2S092NG51Vm94UHFVZE5uRi91UUEwNmNHZkhjTnZSbgpFbGZZVDJ1VWtaT3RKdEV4eTdyRTduU0pmd0tCZ1FEbW1ubWREUmdDeTExNGh2SmVMbFdtbFczWG0vRkp2Mkg2CkdmaTRSb1hvdGJ0bVJpM21VOTJubGNRR20wdGkyWUVqOHBtQjlsTmxvenU5SHJ6V3V1eEpjTm5UZ1Y4SndqVFMKVUt5MUVBTUxsSTFhSWpCTFFFZm1FaTc5cTlLMTNLWGUrZkFjQ3c4YjBWYVdwbEZqbmxXY1h4eDRtWUxacWdzSwpnNXkwbStDeFF3S0JnRWhsWGVDeXV2SmNMbUZzWDlEcTFTeFNtdE1mUWZ1K1dBUXRydVNBYkxaQ2tUUjRvRzlICndsNjIrRFBoS2hYdVY1UFVnbUQxa3N5dm9DSVl6MVkxZTVpS2tnNUJPcjAyVnkza2VpVG9RNjZ5elA5TnVZcWsKU1VpWTY3V1JpTmtTQi8xakRoczQ5bTZKY3RMcklweFB0ODVMOVZpa3FVWFQvMnhoTFRrTHZRbXZBb0dBYlVUWgpSMi9DNXVBU1JHQTlUQjlNZW9qbjZYaDlGdUxXdkRtK1B5TTdwSThvWTBmeHkrZ0ZhYmx2ajJuYWlOWmplUE1sCmhnMkFhdkswQmVNZ3UrY0t1Nm43clZycCs2ZkllN2U2Zm5rOTJDamw2Y1cxZUpMVy9zK3k4SVNRYlpoR0NLZ0oKL0YvSkl2ZEl2azNFMXgxWmw2VUJ5cXVDOHp5OXlwZWVrMzRoTkIwQ2dZQUtmRVY1VXZmQVpEckxPUHhXYldHUwpUd282czJpUC85TnBTKzdXU0NzemNtNGF0S1dQYXNNL29oT3NjWEY0cnZjUWkvcEUwV0tUclZqcXliSzZNTWxiCjg3V1E2MElLVERmOHVocUNySzNKTnF2TGZ0aDZHYkZrL1oxQU9KN2pJUzJ3TVJnZ1JFcUkxOXgxcEJNcS8xWHQKMFIxa21NYWpvMlRkdmF2VlVQMTh2UT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K'
kind: Secret
metadata:
  name: ssl-proxy-secret
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: proxy-chat
  labels:
    name: nginx
    role: ssl-proxy
    app: chat
spec:
  ports:
  - name: https
    port: 443
    targetPort: ssl-proxy-https
    protocol: TCP
  - name: http
    port: 80
    targetPort: ssl-proxy-http
    protocol: TCP
  selector:
    name: nginx
    role: ssl-proxy
    app: chat
  type: LoadBalancer
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: proxy-chat
  labels:
    name: nginx
    role: ssl-proxy
    app: chat
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
    app: chat
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
        app: chat
    spec:
      containers:
      - name: nginx-ssl-proxy
        image: dainisl/nginx-ssl-proxy:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_HOST_ENV_NAME
          value: CHAT_SERVICE_HOST
        - name: SERVICE_PORT_ENV_NAME
          value: CHAT_SERVICE_PORT
        - name: ENABLE_SSL
          value: 'true'
        ports:
        - name: ssl-proxy-http
          containerPort: 80
        - name: ssl-proxy-https
          containerPort: 443
        volumeMounts:
        - name: ssl-proxy-secret
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: ssl-proxy-secret
        secret:
          secretName: ssl-proxy-secret
